export const assistantGraphMockData = {
  summary: {
    incident: "SOC-12345 phishing and endpoint execution investigation",
    risk: "High",
    confidence: "Medium",
    score: 82,
    lastSeen: "2026-05-18T08:42:00Z",
    investigationType: "generic_multi_cluster_investigation",
    interpretation: "A phishing URL was delivered by email, queried by an endpoint, and followed by suspicious process execution. The graph is intentionally modeled as evidence relationships, not assumed compromise.",
  },
  recommendedActions: [
    "Review email delivery and click telemetry for affected users.",
    "Search endpoint logs for the suspicious process and file hash.",
    "Pivot suspicious indicators into OpenCTI for enrichment.",
    "Confirm whether network controls blocked the destination.",
  ],
  nodes: [
    { id: "alert:SOC-12345", type: "alert", label: "SOC-12345 Phishing Investigation", value: "SOC-12345", severity: "high", source: ["Exabeam"], metadata: { role: "primary_alert", riskScore: 82, firstSeen: "2026-05-18T08:10:00Z", lastSeen: "2026-05-18T08:42:00Z" }, evidence: ["alert-4412"] },
    { id: "email:msg-884", type: "email", label: "Credential notice email", value: "msg-884", severity: "medium", source: ["Microsoft 365"], metadata: { firstSeen: "2026-05-18T08:10:00Z" }, evidence: ["m365-message-trace"] },
    { id: "user:ana@example.com", type: "user", label: "ana@example.com", value: "ana@example.com", severity: "medium", source: ["Microsoft 365", "Okta"], metadata: { firstSeen: "2026-05-18T08:11:00Z" }, evidence: ["okta-auth-22"] },
    { id: "host:finance-lt-22", type: "host", label: "finance-lt-22", value: "finance-lt-22", severity: "medium", source: ["SentinelOne"], metadata: { lastSeen: "2026-05-18T08:39:00Z" }, evidence: ["s1-agent-882"] },
    { id: "url:hxxps-example-com-login", type: "url", label: "hxxps://example.com/login", value: "hxxps://example.com/login", severity: "high", source: ["Cloudflare", "OpenCTI"], metadata: { verdict: "suspicious", riskScore: 86 }, evidence: ["cf-dns-17"] },
    { id: "domain:example.com", type: "domain", label: "example.com", value: "example.com", severity: "high", source: ["Cloudflare", "OpenCTI"], metadata: { verdict: "suspicious" }, evidence: ["opencti-indicator-91"] },
    { id: "ip:203.0.113.44", type: "ip", label: "203.0.113.44", value: "203.0.113.44", severity: "high", source: ["Palo Alto", "OpenCTI"], metadata: { verdict: "malicious" }, evidence: ["pan-traffic-910"] },
    { id: "process:powershell", type: "process", label: "powershell.exe", value: "powershell.exe -nop -w hidden", severity: "high", source: ["SentinelOne"], metadata: { firstSeen: "2026-05-18T08:34:00Z" }, evidence: ["s1-process-331"] },
    { id: "file:invoice-js", type: "file", label: "invoice.js", value: "C:\\Users\\Ana\\Downloads\\invoice.js", severity: "high", source: ["SentinelOne"], metadata: { riskScore: 78 }, evidence: ["s1-file-12"] },
    { id: "hash:sha256-demo", type: "hash", label: "sha256:91ab...7781", value: "91ab4d-demo-7781", severity: "high", source: ["Trend Micro", "OpenCTI"], metadata: { verdict: "suspicious" }, evidence: ["tm-detection-2"] },
    { id: "mitre:T1059", type: "mitre", label: "T1059 Command Interpreter", value: "T1059", severity: "medium", source: ["MITRE ATT&CK"], metadata: {}, evidence: ["rule-map"] },
    { id: "mitre:T1105", type: "mitre", label: "T1105 Ingress Tool Transfer", value: "T1105", severity: "medium", source: ["MITRE ATT&CK"], metadata: {}, evidence: ["rule-map"] },
  ],
  edges: [
    { id: "edge-alert-email", source: "alert:SOC-12345", target: "email:msg-884", type: "contains_indicator", label: "contains indicator", confidence: 90, sourceName: "Exabeam" },
    { id: "edge-email-user", source: "email:msg-884", target: "user:ana@example.com", type: "delivered_to", label: "delivered to", confidence: 95, sourceName: "Microsoft 365" },
    { id: "edge-user-host", source: "user:ana@example.com", target: "host:finance-lt-22", type: "logged_in", label: "logged in", confidence: 80, sourceName: "Okta" },
    { id: "edge-email-url", source: "email:msg-884", target: "url:hxxps-example-com-login", type: "email_delivered_url", label: "delivered URL", confidence: 88, sourceName: "Microsoft 365" },
    { id: "edge-url-domain", source: "url:hxxps-example-com-login", target: "domain:example.com", type: "hosted_on", label: "hosted on", confidence: 95, sourceName: "Cloudflare" },
    { id: "edge-domain-ip", source: "domain:example.com", target: "ip:203.0.113.44", type: "resolved_to", label: "resolved to", confidence: 92, sourceName: "Cloudflare" },
    { id: "edge-host-domain", source: "host:finance-lt-22", target: "domain:example.com", type: "queried", label: "queried", confidence: 76, sourceName: "Cloudflare" },
    { id: "edge-process-ip", source: "process:powershell", target: "ip:203.0.113.44", type: "contacted", label: "contacted", confidence: 70, sourceName: "Palo Alto" },
    { id: "edge-file-process", source: "file:invoice-js", target: "process:powershell", type: "executed", label: "executed", confidence: 72, sourceName: "SentinelOne" },
    { id: "edge-file-hash", source: "file:invoice-js", target: "hash:sha256-demo", type: "detected_by", label: "detected by", confidence: 86, sourceName: "Trend Micro" },
    { id: "edge-alert-mitre-1", source: "alert:SOC-12345", target: "mitre:T1059", type: "mapped_to_mitre", label: "mapped to MITRE", confidence: 80, sourceName: "Exabeam" },
    { id: "edge-alert-mitre-2", source: "alert:SOC-12345", target: "mitre:T1105", type: "mapped_to_mitre", label: "mapped to MITRE", confidence: 65, sourceName: "Exabeam" },
  ],
};
