"""
Export Service — generates PDF, Markdown, and JSON exports.

PDF uses WeasyPrint (HTML → PDF). Falls back to simple HTML if WeasyPrint
is not installed.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from io import BytesIO
from typing import Optional

logger = logging.getLogger(__name__)


def export_json(evidence: dict, report: dict, detail: dict) -> bytes:
    """Export full investigation as JSON."""
    result = {
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "investigation": detail,
        "evidence": evidence,
        "report": report,
    }
    return json.dumps(result, indent=2, default=str).encode("utf-8")


def export_markdown(evidence: dict, report: dict, detail: dict) -> str:
    """Export investigation as Markdown report."""
    domain = detail.get("domain", "Unknown")
    classification = (report.get("classification") or "inconclusive").upper()
    confidence = report.get("confidence", "?")
    risk_score = report.get("risk_score", "?")
    action = (report.get("recommended_action") or "monitor").upper()

    lines = [
        f"# Threat Investigation Report: {domain}",
        "",
        f"**Classification:** {classification}  ",
        f"**Confidence:** {confidence}  ",
        f"**Risk Score:** {risk_score}/100  ",
        f"**Recommended Action:** {action}  ",
        f"**Date:** {detail.get('created_at', 'N/A')}  ",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        report.get("primary_reasoning", "No reasoning provided."),
        "",
        "## Hypothesis Comparison",
        "",
        "### Legitimate Hypothesis",
        report.get("legitimate_explanation", "N/A"),
        "",
        "### Malicious Hypothesis",
        report.get("malicious_explanation", "N/A"),
        "",
        "## Recommended Steps",
        "",
    ]

    for i, step in enumerate(report.get("recommended_steps", []), 1):
        lines.append(f"{i}. {step}")

    lines.extend(["", "## Findings", ""])
    for f in report.get("findings", []):
        lines.append(f"### [{f.get('severity', 'info').upper()}] {f.get('title', 'Untitled')}")
        lines.append(f"{f.get('description', '')}")
        if f.get("ttp"):
            lines.append(f"*TTP: {f['ttp']}*")
        lines.append("")

    lines.extend(["## Indicators of Compromise", "", "| Type | Value | Context | Confidence |",
                   "|------|-------|---------|------------|"])
    for ioc in report.get("iocs", []):
        lines.append(f"| {ioc.get('type', '?')} | `{ioc.get('value', '?')}` | {ioc.get('context', '')} | {ioc.get('confidence', '?')} |")

    # Technical evidence summary
    lines.extend(["", "## Technical Evidence Summary", ""])

    dns = evidence.get("dns", {})
    lines.append(f"**DNS A Records:** {', '.join(dns.get('a', []))}")
    lines.append(f"**Name Servers:** {', '.join(dns.get('ns', []))}")
    lines.append(f"**DMARC:** {dns.get('dmarc', 'Not configured')}")

    tls = evidence.get("tls", {})
    lines.append(f"**TLS Issuer:** {tls.get('issuer_org', 'N/A')}")
    lines.append(f"**TLS SANs:** {len(tls.get('sans', []))} entries")

    hosting = evidence.get("hosting", {})
    lines.append(f"**Hosting:** {hosting.get('asn_org', 'N/A')} ({hosting.get('country', '?')})")

    whois = evidence.get("whois", {})
    lines.append(f"**Registrar:** {whois.get('registrar', 'N/A')}")
    lines.append(f"**Domain Age:** {whois.get('domain_age_days', '?')} days")

    lines.extend([
        "",
        "---",
        f"*Generated by Threat Investigator v1.0.0 at {datetime.now(timezone.utc).isoformat()}*",
    ])

    return "\n".join(lines)


def export_pdf(evidence: dict, report: dict, detail: dict) -> bytes:
    """
    Export investigation as PDF.
    Uses WeasyPrint to render HTML → PDF.
    """
    html = _build_pdf_html(evidence, report, detail)

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except ImportError:
        logger.warning("WeasyPrint not installed — returning HTML instead of PDF")
        return html.encode("utf-8")
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        # Fallback: return HTML
        return html.encode("utf-8")


def _build_pdf_html(evidence: dict, report: dict, detail: dict) -> str:
    """Build the HTML template for PDF rendering."""
    domain = detail.get("domain", "Unknown")
    classification = (report.get("classification") or "inconclusive").upper()
    confidence = report.get("confidence", "?")
    risk_score = report.get("risk_score", "?")
    action = (report.get("recommended_action") or "monitor").upper()
    date = detail.get("created_at", "N/A")

    # Classification colors
    colors = {
        "BENIGN": "#10b981",
        "SUSPICIOUS": "#f59e0b",
        "MALICIOUS": "#ef4444",
        "INCONCLUSIVE": "#64748b",
    }
    cls_color = colors.get(classification, "#64748b")

    # Build findings HTML
    findings_html = ""
    for f in report.get("findings", []):
        sev = f.get("severity", "info").upper()
        findings_html += f"""
        <div style="border-left: 3px solid {colors.get(sev, '#64748b')}; padding: 8px 12px; margin-bottom: 8px; background: #f8fafc;">
            <strong>[{sev}]</strong> {f.get('title', '')}
            <div style="color: #64748b; font-size: 12px; margin-top: 4px;">{f.get('description', '')}</div>
        </div>"""

    # Build IOCs table
    iocs_html = ""
    for ioc in report.get("iocs", []):
        iocs_html += f"""
        <tr>
            <td style="padding: 4px 8px; font-size: 12px;">{ioc.get('type', '?')}</td>
            <td style="padding: 4px 8px; font-family: monospace; font-size: 11px;">{ioc.get('value', '?')}</td>
            <td style="padding: 4px 8px; font-size: 12px;">{ioc.get('context', '')}</td>
        </tr>"""

    # Steps
    steps_html = ""
    for i, step in enumerate(report.get("recommended_steps", []), 1):
        steps_html += f"<li>{step}</li>"

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: -apple-system, sans-serif; color: #1e293b; margin: 40px; font-size: 13px; line-height: 1.6; }}
        h1 {{ font-size: 20px; border-bottom: 2px solid #1e293b; padding-bottom: 8px; }}
        h2 {{ font-size: 15px; color: #3b82f6; margin-top: 24px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }}
        .classification {{ display: inline-block; padding: 8px 20px; background: {cls_color}; color: white; font-weight: bold; font-size: 16px; border-radius: 6px; letter-spacing: 0.1em; }}
        .meta {{ color: #64748b; font-size: 12px; }}
        .meta-grid {{ display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; gap: 12px; margin: 16px 0; }}
        .meta-item {{ padding: 8px 12px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; }}
        .meta-label {{ font-size: 10px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.08em; }}
        .meta-value {{ font-size: 14px; font-weight: 600; }}
        table {{ width: 100%; border-collapse: collapse; margin: 8px 0; }}
        th, td {{ text-align: left; padding: 4px 8px; border-bottom: 1px solid #e2e8f0; font-size: 12px; }}
        th {{ background: #f1f5f9; font-weight: 600; }}
        .hypothesis {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }}
        .hypothesis > div {{ padding: 12px; border-radius: 6px; font-size: 12px; }}
        .legit {{ background: #f0fdf4; border: 1px solid #bbf7d0; }}
        .malicious {{ background: #fef2f2; border: 1px solid #fecaca; }}
        .footer {{ margin-top: 32px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }}
    </style>
</head>
<body>
    <h1>Threat Investigation Report</h1>
    <div class="meta">Domain: <strong>{domain}</strong> · Date: {date}</div>

    <div class="meta-grid">
        <div class="meta-item"><div class="meta-label">Classification</div><div class="meta-value" style="color:{cls_color}">{classification}</div></div>
        <div class="meta-item"><div class="meta-label">Confidence</div><div class="meta-value">{confidence}</div></div>
        <div class="meta-item"><div class="meta-label">Risk Score</div><div class="meta-value">{risk_score}/100</div></div>
        <div class="meta-item"><div class="meta-label">Action</div><div class="meta-value">{action}</div></div>
    </div>

    <h2>Primary Reasoning</h2>
    <p>{report.get('primary_reasoning', 'N/A')}</p>

    <h2>Hypothesis Comparison</h2>
    <div class="hypothesis">
        <div class="legit"><strong>✓ Legitimate</strong><br>{report.get('legitimate_explanation', 'N/A')}</div>
        <div class="malicious"><strong>✗ Malicious</strong><br>{report.get('malicious_explanation', 'N/A')}</div>
    </div>

    <h2>Recommended Steps</h2>
    <ol>{steps_html}</ol>

    <h2>Findings</h2>
    {findings_html or '<p style="color: #94a3b8;">No findings.</p>'}

    <h2>Indicators of Compromise</h2>
    {f'<table><tr><th>Type</th><th>Value</th><th>Context</th></tr>{iocs_html}</table>' if iocs_html else '<p style="color: #94a3b8;">No IOCs.</p>'}

    <div class="footer">Generated by Threat Investigator v1.0.0 · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</div>
</body>
</html>"""
