"""
Export Service — generates PDF, Markdown, and JSON exports.

PDF uses WeasyPrint (HTML → PDF). Falls back to simple HTML if WeasyPrint
is not installed.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from io import BytesIO
from typing import Optional

logger = logging.getLogger(__name__)


def export_json(evidence: dict, report: dict, detail: dict) -> bytes:
    """Export full investigation as JSON."""
    result = {
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "investigation": detail,
        "evidence": evidence,
        "report": report,
    }
    return json.dumps(result, indent=2, default=str).encode("utf-8")


def export_markdown(evidence: dict, report: dict, detail: dict) -> str:
    """Export investigation as Markdown report."""
    domain = detail.get("domain", "Unknown")
    classification = (report.get("classification") or "inconclusive").upper()
    confidence = report.get("confidence", "?")
    risk_score = report.get("risk_score", "?")
    action = (report.get("recommended_action") or "monitor").upper()

    lines = [
        f"# Threat Investigation Report: {domain}",
        "",
        f"**Classification:** {classification}  ",
        f"**Confidence:** {confidence}  ",
        f"**Risk Score:** {risk_score}/100  ",
        f"**Recommended Action:** {action}  ",
        f"**Date:** {detail.get('created_at', 'N/A')}  ",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        report.get("primary_reasoning", "No reasoning provided."),
        "",
        "## Hypothesis Comparison",
        "",
        "### Legitimate Hypothesis",
        report.get("legitimate_explanation", "N/A"),
        "",
        "### Malicious Hypothesis",
        report.get("malicious_explanation", "N/A"),
        "",
        "## Recommended Steps",
        "",
    ]

    for i, step in enumerate(report.get("recommended_steps", []), 1):
        lines.append(f"{i}. {step}")

    lines.extend(["", "## Findings", ""])
    for f in report.get("findings", []):
        lines.append(f"### [{f.get('severity', 'info').upper()}] {f.get('title', 'Untitled')}")
        lines.append(f"{f.get('description', '')}")
        if f.get("ttp"):
            lines.append(f"*TTP: {f['ttp']}*")
        lines.append("")

    lines.extend(["## Indicators of Compromise", "", "| Type | Value | Context | Confidence |",
                   "|------|-------|---------|------------|"])
    for ioc in report.get("iocs", []):
        lines.append(f"| {ioc.get('type', '?')} | `{ioc.get('value', '?')}` | {ioc.get('context', '')} | {ioc.get('confidence', '?')} |")

    # Technical evidence summary
    lines.extend(["", "## Technical Evidence Summary", ""])

    dns = evidence.get("dns", {})
    lines.append(f"**DNS A Records:** {', '.join(dns.get('a', []))}")
    lines.append(f"**Name Servers:** {', '.join(dns.get('ns', []))}")
    lines.append(f"**DMARC:** {dns.get('dmarc', 'Not configured')}")

    tls = evidence.get("tls", {})
    lines.append(f"**TLS Issuer:** {tls.get('issuer_org', 'N/A')}")
    lines.append(f"**TLS SANs:** {len(tls.get('sans', []))} entries")

    hosting = evidence.get("hosting", {})
    lines.append(f"**Hosting:** {hosting.get('asn_org', 'N/A')} ({hosting.get('country', '?')})")

    whois = evidence.get("whois", {})
    lines.append(f"**Registrar:** {whois.get('registrar', 'N/A')}")
    lines.append(f"**Domain Age:** {whois.get('domain_age_days', '?')} days")

    lines.extend([
        "",
        "---",
        f"*Generated by Threat Investigator v1.0.0 at {datetime.now(timezone.utc).isoformat()}*",
    ])

    return "\n".join(lines)


def export_pdf(evidence: dict, report: dict, detail: dict) -> bytes:
    """
    Export investigation as PDF.
    Uses WeasyPrint to render HTML → PDF.
    """
    html = _build_pdf_html(evidence, report, detail)

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except ImportError:
        logger.warning("WeasyPrint not installed — returning HTML instead of PDF")
        return html.encode("utf-8")
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        # Fallback: return HTML
        return html.encode("utf-8")


_CLASSIFICATION_COLORS = {
    "BENIGN": "#10b981",
    "SUSPICIOUS": "#f59e0b",
    "MALICIOUS": "#ef4444",
    "INCONCLUSIVE": "#64748b",
}

_TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "..", "templates")


def _build_pdf_html(evidence: dict, report: dict, detail: dict) -> str:
    """Build HTML for PDF rendering using Jinja2 template."""
    domain = detail.get("domain", "Unknown")
    classification = (report.get("classification") or "inconclusive").upper()
    cls_color = _CLASSIFICATION_COLORS.get(classification, "#64748b")
    investigation_id = detail.get("id", "")
    generated_at = datetime.now(timezone.utc).isoformat()

    try:
        from jinja2 import Environment, FileSystemLoader, select_autoescape
        env = Environment(
            loader=FileSystemLoader(_TEMPLATES_DIR),
            autoescape=select_autoescape(["html"]),
        )
        template = env.get_template("report.html")
        return template.render(
            domain=domain,
            classification=classification,
            cls_color=cls_color,
            investigation_id=investigation_id,
            generated_at=generated_at,
            detail=detail,
            evidence=evidence,
            report=report,
        )
    except Exception as e:
        logger.warning(f"Jinja2 template rendering failed ({e}), falling back to basic HTML")
        return _build_fallback_html(domain, classification, cls_color, report, generated_at)


def _build_fallback_html(
    domain: str, classification: str, cls_color: str, report: dict, generated_at: str
) -> str:
    """Minimal fallback HTML if Jinja2 template fails."""
    steps = "".join(f"<li>{s}</li>" for s in report.get("recommended_steps", []))
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>body{{font-family:sans-serif;color:#1e293b;margin:40px;font-size:13px;line-height:1.6}}
h1{{font-size:20px}}h2{{font-size:15px;color:#3b82f6;margin-top:20px}}</style>
</head><body>
<h1>Threat Investigation Report — {domain}</h1>
<p><strong>Classification:</strong> <span style="color:{cls_color}">{classification}</span> &nbsp;
<strong>Risk:</strong> {report.get('risk_score','?')}/100</p>
<h2>Primary Reasoning</h2><p>{report.get('primary_reasoning','N/A')}</p>
<h2>Recommended Steps</h2><ol>{steps}</ol>
<p style="color:#94a3b8;font-size:10px">Generated {generated_at[:19]} UTC</p>
</body></html>"""
