"use client";

import React from "react";
import { AnalystReport } from "@/lib/types";
import ClassificationBadge from "@/components/investigation/ClassificationBadge";

interface Props {
  report: AnalystReport;
}

export default function ExecutiveSummaryTab({ report }: Props) {
  const reasoningText = report?.primary_reasoning || "No reasoning provided.";
  const reasoningParagraphs = reasoningText
    .split(/\n{2,}/)
    .map((part) => part.trim())
    .filter(Boolean);

  return (
    <div>
      <ClassificationBadge
        classification={report?.classification || "inconclusive"}
        confidence={report?.confidence || "low"}
        riskScore={report?.risk_score}
      />

      <Section title="Primary Reasoning">
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {(reasoningParagraphs.length ? reasoningParagraphs : [reasoningText]).map((paragraph, index) => (
            <p key={index} style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.8, margin: 0 }}>
              {paragraph}
            </p>
          ))}
        </div>
        <div style={{ marginTop: 10, display: "flex", alignItems: "center", gap: 6 }}>
          <span style={{ fontSize: 10, color: "var(--text-muted)", fontFamily: "var(--font-sans)" }}>
            Generated by
          </span>
          <span style={{
            fontSize: 10,
            fontFamily: "var(--font-mono)",
            fontWeight: 600,
            padding: "2px 8px",
            borderRadius: "var(--radius-sm)",
            border: `1px solid ${report?.ai_model?.startsWith("claude-") ? "#f97316" : "#60a5fa"}`,
            color: report?.ai_model?.startsWith("claude-") ? "#f97316" : "#60a5fa",
            background: report?.ai_model?.startsWith("claude-") ? "rgba(249,115,22,0.08)" : "rgba(96,165,250,0.08)",
          }}>
            {report?.ai_model
              ? report.ai_model.startsWith("claude-sonnet") ? "Claude Sonnet 4.6"
              : report.ai_model.startsWith("claude-haiku") ? "Claude Haiku 4.5"
              : report.ai_model.startsWith("claude-opus") ? "Claude Opus 4.6"
              : report.ai_model === "gpt-5-mini" ? "GPT-5 Mini"
              : report.ai_model === "gpt-4o-mini" ? "GPT-4o Mini"
              : report.ai_model === "gpt-4o" ? "GPT-4o"
              : report.ai_model
              : "Automated (rule-based)"}
          </span>
        </div>
      </Section>

    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 32 }}>
      <div style={{
        fontSize: 13, fontWeight: 600, color: "var(--accent)",
        letterSpacing: "0.01em", marginBottom: 14,
        paddingBottom: 8, borderBottom: "1px solid var(--border)",
        fontFamily: "var(--font-sans)",
      }}>
        {title}
      </div>
      {children}
    </div>
  );
}
